apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-wt5v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component-wt5v
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-python-basrlfa
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-python-basic-rhtap-devfile-multi-component-wt5v
    weight: null
status: {}
